replicaCount: 1

image:
  repository: changeme
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: changeme
env:
  BACKEND_URL: changeme

ingress:
  enabled: true
  host: changeme
  path: /
  pathType: Prefix
  entryPoint: websecure
  tls:
    enabled: true
    secretName: tls-secret

